server {
    listen 80;
    server_name localhost dailysharkfinds.com www.dailysharkfinds.com;
    root /var/www/html/public;
    index index.php index.html index.htm;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_param SERVER_PORT 443;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
