server {
    listen 80;
    server_name homewellnessforyou.com www.homewellnessforyou.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name homewellnessforyou.com www.homewellnessforyou.com;
    root /var/www/html/public;
    index index.php index.html index.htm;

    ssl_certificate /etc/letsencrypt/live/homewellnessforyou.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/homewellnessforyou.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}